using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WindowsInput.Native;

namespace TouchBoardWinServer
{
    static class Constants
    {
        public static Dictionary<VirtualKeyCode, int> InterceptorWrapper = new Dictionary<VirtualKeyCode, int>() {

            {  VirtualKeyCode.TAB, 15},
            {  VirtualKeyCode.BACK, 14},
            {  VirtualKeyCode.RETURN, 28},
            {  VirtualKeyCode.CAPITAL, 58},
            {  VirtualKeyCode.ESCAPE, 1},
            {  VirtualKeyCode.SPACE, 57},
            {  VirtualKeyCode.PRIOR, 73},
            {  VirtualKeyCode.NEXT, 81},
            {  VirtualKeyCode.END, 79},
            {  VirtualKeyCode.HOME, 71},
            {  VirtualKeyCode.LEFT, 75},
            {  VirtualKeyCode.UP, 72},
            {  VirtualKeyCode.RIGHT, 77},
            {  VirtualKeyCode.DOWN, 80},
            {  VirtualKeyCode.INSERT, 82},
            {  VirtualKeyCode.DELETE, 83},
            {  VirtualKeyCode.VK_0, 11},
            {  VirtualKeyCode.VK_1, 2},
            {  VirtualKeyCode.VK_2, 3},
            {  VirtualKeyCode.VK_3, 4},
            {  VirtualKeyCode.VK_4, 5},
            {  VirtualKeyCode.VK_5, 6},
            {  VirtualKeyCode.VK_6, 7},
            {  VirtualKeyCode.VK_7, 8},
            {  VirtualKeyCode.VK_8, 9},
            {  VirtualKeyCode.VK_9, 10},
            {  VirtualKeyCode.VK_A, 30},
            {  VirtualKeyCode.VK_B, 48},
            {  VirtualKeyCode.VK_C, 46},
            {  VirtualKeyCode.VK_D, 32},
            {  VirtualKeyCode.VK_E, 18},
            {  VirtualKeyCode.VK_F, 33},
            {  VirtualKeyCode.VK_G, 34},
            {  VirtualKeyCode.VK_H, 35},
            {  VirtualKeyCode.VK_I, 23},
            {  VirtualKeyCode.VK_J, 36},
            {  VirtualKeyCode.VK_K, 37},
            {  VirtualKeyCode.VK_L, 38},
            {  VirtualKeyCode.VK_M, 50},
            {  VirtualKeyCode.VK_N, 49},
            {  VirtualKeyCode.VK_O, 24},
            {  VirtualKeyCode.VK_P, 25},
            {  VirtualKeyCode.VK_Q, 16},
            {  VirtualKeyCode.VK_R, 19},
            {  VirtualKeyCode.VK_S, 31},
            {  VirtualKeyCode.VK_T, 20},
            {  VirtualKeyCode.VK_U, 22},
            {  VirtualKeyCode.VK_V, 47},
            {  VirtualKeyCode.VK_W, 17},
            {  VirtualKeyCode.VK_X, 45},
            {  VirtualKeyCode.VK_Y, 21},
            {  VirtualKeyCode.VK_Z, 44},
            {  VirtualKeyCode.LWIN, 91},
            {  VirtualKeyCode.RWIN, 91},
            {  VirtualKeyCode.NUMPAD0, 82},
            {  VirtualKeyCode.NUMPAD1, 79},
            {  VirtualKeyCode.NUMPAD2, 80},
            {  VirtualKeyCode.NUMPAD3, 81},
            {  VirtualKeyCode.NUMPAD4, 75},
            {  VirtualKeyCode.NUMPAD5, 76},
            {  VirtualKeyCode.NUMPAD6, 77},
            {  VirtualKeyCode.NUMPAD7, 71},
            {  VirtualKeyCode.NUMPAD8, 72},
            {  VirtualKeyCode.NUMPAD9, 73},
            {  VirtualKeyCode.MULTIPLY, 55},
            {  VirtualKeyCode.ADD, 78},
            {  VirtualKeyCode.SEPARATOR, 74},
            {  VirtualKeyCode.SUBTRACT, 74},
            {  VirtualKeyCode.DECIMAL, 83},
            {  VirtualKeyCode.DIVIDE, 53},
            {  VirtualKeyCode.F1, 59},
            {  VirtualKeyCode.F2, 60},
            {  VirtualKeyCode.F3, 61},
            {  VirtualKeyCode.F4, 62},
            {  VirtualKeyCode.F5, 63},
            {  VirtualKeyCode.F6, 64},
            {  VirtualKeyCode.F7, 65},
            {  VirtualKeyCode.F8, 66},
            {  VirtualKeyCode.F9, 67},
            {  VirtualKeyCode.F10, 68},
            {  VirtualKeyCode.F11, 87},
            {  VirtualKeyCode.F12, 88},
            {  VirtualKeyCode.F13, 88},
            {  VirtualKeyCode.F14, 88},
            {  VirtualKeyCode.F15, 88},


            {  VirtualKeyCode.NUMLOCK, 69},
            {  VirtualKeyCode.LSHIFT, 42},
            {  VirtualKeyCode.RSHIFT, 54},
            {  VirtualKeyCode.LCONTROL, 29},
            {  VirtualKeyCode.RCONTROL, 29},
            {  VirtualKeyCode.LMENU, 56 }, //todo
            {  VirtualKeyCode.RMENU, 56},
            {  VirtualKeyCode.OEM_1, 39}, //semicolon

            {  VirtualKeyCode.OEM_PLUS, 13},
            {  VirtualKeyCode.OEM_COMMA, 51},
            {  VirtualKeyCode.OEM_MINUS, 12},
            {  VirtualKeyCode.OEM_PERIOD, 52},
            {  VirtualKeyCode.OEM_2, 53},
            {  VirtualKeyCode.OEM_3, 41}, 
            {  VirtualKeyCode.OEM_4, 26},
            {  VirtualKeyCode.OEM_5, 43}, 
            {  VirtualKeyCode.OEM_6, 27},
            {  VirtualKeyCode.OEM_7, 0x27},

        };
    }
}
